Create gif_patrol_cyc bash script to generate patrol-cycle gifs.

diff --git a/convert_vid_to_gif b/convert_vid_to_gif
--- a/convert_vid_to_gif
+++ b/convert_vid_to_gif
@@ -19,22 +19,32 @@ FILENAME_NO_EXT=$(basename "${FILE_PATH}" "."${EXT})
 FILE_DIR_OG=$(dirname "${FILE_PATH}")
 # https://linuxhandbook.com/dirname/
 
-NEW_EXT=".gif"
+NEW_EXT="gif"
 # put timestamps in output filename
 if [[ $# == 2 ]];
 then
-  FILEPATH_OUT="${FILEPATH_NO_EXT}_${2}s-${NEW_EXT}"
+  FILEPATH_OUT="${FILEPATH_NO_EXT}_${2}s-.${NEW_EXT}"
 elif [[ $# == 3 ]];
 then
-  FILEPATH_OUT="${FILEPATH_NO_EXT}_${2}-${3}s${NEW_EXT}"
+  FILEPATH_OUT="${FILEPATH_NO_EXT}_${2}-${3}s.${NEW_EXT}"
 else
-  FILEPATH_OUT="${FILEPATH_NO_EXT}${NEW_EXT}"
+  FILEPATH_OUT="${FILEPATH_NO_EXT}.${NEW_EXT}"
+fi
+
+# Validate input path
+if [[ -e "${FILE_PATH}" ]];
+then
+  :
+else
+  printf "\nSpecified file cannot be found.\n"
+  exit 1
 fi
 
 # Check for existence of output file before attempting conversion.
 # ffmpeg has this check, but it requires the rest of the verbose output
 # (which is suppressed below)
-if [[ -f "${FILEPATH_OUT}" ]];
+# Check for both resolvable path and broken symlink # https://unix.stackexchange.com/a/550837
+if [[ -e "${FILEPATH_OUT}" ]] || [[ -h "${FILEPATH_OUT}" ]];
 then
   printf "\nTarget file exists. Overwrite? [Y/N]\n"
   read -p ">" answer
