Add EXIF-comment transcription to conversion bash scripts.

diff --git a/convert_vid_to_gif b/convert_vid_to_gif
--- a/convert_vid_to_gif
+++ b/convert_vid_to_gif
@@ -5,7 +5,7 @@
 # Start and end time can either be integers or in "00:00.00" format
 
 
-
+SCRIPT_DIR="$(realpath "$(dirname "${0}")")"
 FILE_PATH="$(realpath "${1}")"
 # https://code-maven.com/bash-absolute-path
 FILEPATH_NO_EXT="${FILE_PATH%.*}"
@@ -88,7 +88,16 @@ fi
 FFMPEG_RETURN=$? # gets return value of last command executed.
 if [ ${FFMPEG_RETURN} == 0 ]
 then
-  printf "SUCCESS\n"
+  # transcribe EXIF comment, if present
+  "${SCRIPT_DIR}"/transfer_exif_comment "${FILE_PATH}" "${FILEPATH_OUT}"
+  COMMENT_RETURN=$? # gets return value of last command executed.
+  if [ ${COMMENT_RETURN} == 0 ];
+  then
+    printf "SUCCESS\n"
+  else
+    printf "FAIL\nEXIF-comment transfer unsuccessful.\n"
+    exit 1
+  fi
   # Open gif so user can confirm valid output file.
   sleep 1
   xdg-open 2>/dev/null "${FILEPATH_OUT}"
diff --git a/gif_patrol_cyc b/gif_patrol_cyc
--- a/gif_patrol_cyc
+++ b/gif_patrol_cyc
@@ -209,7 +209,16 @@ fi
 PATROL_CYC_RETURN=$? # gets return value of last command executed.
 if [ ${PATROL_CYC_RETURN} == 0 ]
 then
-  printf "SUCCESS\n"
+  # transcribe EXIF comment, if present
+  "${SCRIPT_DIR}"/transfer_exif_comment "${FILE_PATH}" "${FILEPATH_OUT}"
+  COMMENT_RETURN=$? # gets return value of last command executed.
+  if [ ${COMMENT_RETURN} == 0 ];
+  then
+    printf "SUCCESS\n"
+  else
+    printf "FAIL\nEXIF-comment transfer unsuccessful.\n"
+    exit 1
+  fi
   # Open gif so user can confirm valid output file.
   nemo "${TEMP_FOLDER}"
   sleep 1
diff --git a/trim_to_mp4 b/trim_to_mp4
--- a/trim_to_mp4
+++ b/trim_to_mp4
@@ -5,7 +5,7 @@
 # If neither timestamp specified, can be used to just convert input vid to mp4 format.
 # works w/ WEBM, MP4, MOV, and GIF input formats (at least)
 
-
+SCRIPT_DIR="$(realpath "$(dirname "${0}")")"
 FILE_PATH="$(realpath "${1}")"
 # https://code-maven.com/bash-absolute-path
 FILEPATH_NO_EXT="${FILE_PATH%.*}"
@@ -89,7 +89,16 @@ fi
 FFMPEG_RETURN=$? # gets return value of last command executed.
 if [ ${FFMPEG_RETURN} == 0 ]
 then
-  printf "SUCCESS\n"
+  # transcribe EXIF comment, if present
+  "${SCRIPT_DIR}"/transfer_exif_comment "${FILE_PATH}" "${FILEPATH_OUT}"
+  COMMENT_RETURN=$? # gets return value of last command executed.
+  if [ ${COMMENT_RETURN} == 0 ];
+  then
+    printf "SUCCESS\n"
+  else
+    printf "FAIL\nEXIF-comment transfer unsuccessful.\n"
+    exit 1
+  fi
 else
   printf "FAIL\n"
   exit 1
